[tool.poetry]
name = "no-show-app"
version = "0.1"
description = ""
authors = ["Matt Stammers <matthew.stammers@reallyusefulmodels.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "2.2.1"
scikit-learn = "1.4.1.post1"
matplotlib = "3.8.3"
flask = "^3.0.2"
python-dotenv = "^1.0.1"
altair = "^5.2.0"
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
